// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDshWwVO1aQq3Z0reyl5mAE3sT0NyW4Eus',
    appId: '1:19456814207:web:f71161253430d325e6a34a',
    messagingSenderId: '19456814207',
    projectId: 'ugsf-menomics',
    authDomain: 'ugsf-menomics.firebaseapp.com',
    storageBucket: 'ugsf-menomics.appspot.com',
    measurementId: 'G-Z6FFBSBXC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-7DCUcSTQ1C4MO4vzudnwTpwG5FGNh0',
    appId: '1:19456814207:android:7e3df6b99b4c22cde6a34a',
    messagingSenderId: '19456814207',
    projectId: 'ugsf-menomics',
    storageBucket: 'ugsf-menomics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4o_Coh9m2uU_Sq9gOgRy9U-yt12mlSMg',
    appId: '1:19456814207:ios:6c36edd3a69d538ee6a34a',
    messagingSenderId: '19456814207',
    projectId: 'ugsf-menomics',
    storageBucket: 'ugsf-menomics.appspot.com',
    iosClientId: '19456814207-tkia7posvjqrahk61bubq65gro9u5744.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAndMysqlServer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4o_Coh9m2uU_Sq9gOgRy9U-yt12mlSMg',
    appId: '1:19456814207:ios:6c36edd3a69d538ee6a34a',
    messagingSenderId: '19456814207',
    projectId: 'ugsf-menomics',
    storageBucket: 'ugsf-menomics.appspot.com',
    iosClientId: '19456814207-tkia7posvjqrahk61bubq65gro9u5744.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAndMysqlServer',
  );
}
